<?php
defined( 'ABSPATH' ) || exit;

class HOCWP_Theme_Maps_Autocomplete extends HOCWP_Theme_Google_Maps_API {
	public function __construct( $params, $output = '' ) {
		if ( HT()->array_has_value( $params ) ) {
			/*
			 * https://developers.google.com/maps/documentation/places/web-service/autocomplete
			 */
			$defaults = array(
				'input'        => '',
				'location'     => '',
				'strictbounds' => 'true',
				'language'     => get_locale(),
				'types'        => 'establishment'
			);

			$params = wp_parse_args( $params, $defaults );
		}

		parent::__construct( 'place', 'autocomplete', $params, $output );
	}

	public function is_valid() {
		$valid = parent::is_valid(); // TODO: Change the autogenerated stub

		return ( $valid && isset( $this->result->predictions ) && HT()->array_has_value( $this->result->predictions ) );
	}
}