<?php
defined( 'ABSPATH' ) || exit;

class HOCWP_Theme_Maps_Geocode extends HOCWP_Theme_Google_Maps_API {
	public function __construct( $params, $output = '' ) {
		if ( ! is_array( $params ) ) {
			$params = array(
				'address' => $params
			);
		}

		/*
		 * https://developers.google.com/maps/documentation/geocoding/overview
		 */
		$defaults = array(
			'language' => get_locale()
		);

		$key = ht_options()->get_tab( 'google_api_key_ip', '', 'social' );

		if ( ! empty( $key ) ) {
			$defaults['key'] = $key;
		}

		$params = wp_parse_args( $params, $defaults );

		parent::__construct( 'geocode', '', $params, $output );
	}

	public function is_valid() {
		$valid = parent::is_valid(); // TODO: Change the autogenerated stub

		return ( $valid && isset( $this->result->results ) && ht()->array_has_value( $this->result->results ) );
	}
}