<?php
defined( 'ABSPATH' ) || exit;

class HOCWP_Theme_Maps_Distance_Matrix extends HOCWP_Theme_Google_Maps_API {
	public function __construct( $params, $output = '' ) {
		if ( ! is_array( $params ) ) {
			$params = array();
		}

		/*
		 * https://developers.google.com/maps/documentation/distance-matrix/overview
		 */
		$defaults = array(
			'destinations' => '',
			'origins'      => '',
			'language'     => get_locale(),
			'mode'         => 'driving'
		);

		$params = wp_parse_args( $params, $defaults );

		parent::__construct( 'distancematrix', '', $params, $output );
	}

	public function is_valid() {
		$valid = parent::is_valid(); // TODO: Change the autogenerated stub

		return ( $valid && isset( $this->result->rows ) && HT()->array_has_value( $this->result->rows ) );
	}
}