<?php
defined( 'ABSPATH' ) || exit;

class HOCWP_Theme_Maps_Geocode extends HOCWP_Theme_Google_Maps_API {
	public function __construct( $params, $output = '' ) {
		if ( HT()->array_has_value( $params ) ) {
			/*
			 * https://developers.google.com/maps/documentation/geocoding/overview
			 */
			$defaults = array(
				'language' => get_locale()
			);

			$params = wp_parse_args( $params, $defaults );
		}

		parent::__construct( 'geocode', '', $params, $output );
	}

	public function is_valid() {
		$valid = parent::is_valid(); // TODO: Change the autogenerated stub

		return ( $valid && isset( $this->result->results ) && HT()->array_has_value( $this->result->results ) );
	}
}